# Generated by Django 5.0.7 on 2025-03-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_hint_arabic_hint_french_hint_german_hint_japanese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='arabic',
            field=models.CharField(max_length=50, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='french',
            field=models.CharField(max_length=50, verbose_name='French'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='german',
            field=models.CharField(max_length=50, verbose_name='German'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='hintId',
            field=models.CharField(max_length=3, unique=True, verbose_name='Hint ID'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='japanese',
            field=models.CharField(max_length=50, verbose_name='Japanese'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='russian',
            field=models.CharField(max_length=50, verbose_name='Russian'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='word',
            field=models.CharField(max_length=40, verbose_name='Word'),
        ),
    ]
