# Generated by Django 5.0.7 on 2025-05-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_hint_arabic_alter_hint_french_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoGapExercisesId', models.CharField(max_length=2, unique=True, verbose_name='Info Gap Exercises ID')),
                ('infoGapExercisesType', models.CharField(max_length=50, verbose_name='Info Gap Exercise Type')),
                ('infoGapExercisesLevel', models.CharField(max_length=2, verbose_name='Info Gap Exercises Level')),
                ('context', models.CharField(max_length=50, verbose_name='Context')),
                ('scenario', models.CharField(max_length=30, verbose_name='Scenario')),
                ('nativeLanguageId', models.CharField(max_length=1, verbose_name='Native Language ID')),
                ('learningLanguageId', models.CharField(max_length=1, verbose_name='Learning Language ID')),
            ],
        ),
    ]
