# Generated by Django 5.0.7 on 2025-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_infogapexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoGapExerciseId', models.CharField(max_length=2, unique=True, verbose_name='Info Gap Exercise ID')),
                ('infoGapExerciseType', models.CharField(max_length=50, verbose_name='Info Gap Exercise Type')),
                ('infoGapExerciseLevel', models.CharField(max_length=2, verbose_name='Info Gap Exercise Level')),
                ('context', models.CharField(max_length=50, verbose_name='Context')),
                ('scenario', models.CharField(max_length=30, verbose_name='Scenario')),
                ('nativeLanguageId', models.CharField(max_length=1, verbose_name='Native Language ID')),
                ('learningLanguageId', models.CharField(max_length=1, verbose_name='Learning Language ID')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoGapExercises',
        ),
    ]
