# Generated by Django 5.0.7 on 2025-05-08 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_infogapexercise_delete_infogapexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapListDeliContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoGapListDeliContentId', models.CharField(max_length=3, unique=True, verbose_name='info Gap List Deli Content ID')),
                ('item_name', models.CharField(max_length=100)),
                ('correct_price', models.CharField(max_length=20)),
                ('correct_quantity', models.CharField(max_length=50)),
                ('price_options', models.JSONField()),
                ('quantity_options', models.JSONField()),
                ('infoGapExerciseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.infogapexercise')),
            ],
        ),
    ]
