# Generated by Django 5.0.7 on 2025-05-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_infogaplistdelicontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapMapTownCentreContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoGapMapTownCentreContentId', models.CharField(max_length=3, unique=True, verbose_name='info Gap Map Town Centre Content ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('correct_place', models.CharField(max_length=100)),
                ('is_blank', models.BooleanField()),
                ('infoGapExerciseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.infogapexercise')),
            ],
        ),
    ]
