# Generated by Django 5.0.7 on 2025-05-12 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_infogapmaptowncentrecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapMatricesInterviewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoGapMatricesInterviewContentId', models.CharField(max_length=3, unique=True, verbose_name='Info Gap Matrices Interview Content ID')),
                ('label', models.CharField(max_length=100)),
                ('correct_name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('person', models.CharField(max_length=1)),
                ('infoGapExerciseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.infogapexercise')),
            ],
        ),
    ]
