# Generated by Django 5.0.7 on 2025-05-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_infogapmatricesinterviewcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=10, unique=True)),
                ('person_a_joined', models.BooleanField(default=False)),
                ('person_b_joined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.infogapexercise')),
            ],
        ),
    ]
