# Generated by Django 5.0.7 on 2025-05-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_infogapsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGapHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, verbose_name='Word')),
                ('spanish', models.CharField(blank=True, max_length=50, verbose_name='Spanish')),
                ('chinese', models.CharField(blank=True, max_length=50, verbose_name='Chinese')),
                ('italian', models.CharField(blank=True, max_length=50, verbose_name='Italian')),
                ('german', models.CharField(blank=True, max_length=50, verbose_name='German')),
                ('french', models.CharField(blank=True, max_length=50, verbose_name='French')),
                ('arabic', models.CharField(blank=True, max_length=50, verbose_name='Arabic')),
                ('russian', models.CharField(blank=True, max_length=50, verbose_name='Russian')),
                ('japanese', models.CharField(blank=True, max_length=50, verbose_name='Japanese')),
                ('infoGapExerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='events.infogapexercise')),
            ],
        ),
    ]
