# Generated by Django 5.0.7 on 2025-05-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_infogaphint'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogapsession',
            name='person_a_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infogapsession',
            name='person_b_completed',
            field=models.BooleanField(default=False),
        ),
    ]
